"""Tests for cleaning.py: per-kind cleaners, PII and secret handling (written first)."""

import random

import pytest

from viki_slm_125m.data import cleaning

_WORDS = ("company revenue increased during fiscal year compared prior volumes supply chain network "
          "customers inventory orders suppliers shipments warehouse forecast demand margin credit loan "
          "interest payment account balance risk liquidity capital market report quarter agreement "
          "contract delivery logistics procurement planning analysis results management committee "
          "board policy regulation compliance audit statement income expense asset liability equity "
          "growth decline stable average total annual monthly weekly regional global domestic "
          "significant moderate recent following several various certain primary secondary "
          "operations production capacity throughput service level cost price rate volume mix").split()


def prose(n: int, seed: int = 0) -> str:
    rng = random.Random(seed)
    return "\n".join(" ".join(rng.choice(_WORDS) for _ in range(28)) + "." for _ in range(n))


# ---------- PII / secrets ----------

def test_redact_pii_replaces_email_and_public_ip():
    out = cleaning.redact_pii("mail bob.smith@corp.io from 8.8.8.8 today")
    assert "bob.smith@corp.io" not in out and "8.8.8.8" not in out
    assert "user@example.com" in out and "192.0.2.1" in out


def test_redact_pii_keeps_private_and_loopback_ip():
    text = "host 127.0.0.1 and 192.168.1.10 and 10.0.0.5"
    assert cleaning.redact_pii(text) == text


def test_redact_pii_is_idempotent():
    once = cleaning.redact_pii("a@b.com 8.8.4.4")
    assert cleaning.redact_pii(once) == once


@pytest.mark.parametrize("secret", [
    "-----BEGIN RSA PRIVATE KEY-----\nabc\n-----END RSA PRIVATE KEY-----",
    "key = 'AKIAIOSFODNN7EXAMPLE'",
    "token = 'ghp_" + "a" * 36 + "'",
    "hf_" + "b" * 34,
    "sk-" + "c" * 40,
])
def test_has_secret_detects_high_confidence_tokens(secret):
    assert cleaning.has_secret(secret)


def test_has_secret_ignores_normal_code():
    assert not cleaning.has_secret("def add(a, b):\n    return a + b\n")


# ---------- prose ----------

def test_text_keeps_good_prose():
    r = cleaning.clean_document(prose(12), "text")
    assert r.kept and r.reason == "kept"


def test_text_drops_short_documents():
    assert cleaning.clean_document("too short", "text").reason == "too_short"


def test_text_drops_repetitive_documents():
    r = cleaning.clean_document(("buy now cheap pills online store today " * 80 + "\n") * 6, "text")
    assert r.reason == "repetitive"


def test_text_drops_non_latin_script():
    r = cleaning.clean_document(
        "\n".join(["这是一个很长的中文句子用来测试语言过滤器是否正常工作" * 3] * 30), "text")
    assert not r.kept and r.reason in {"too_short", "non_english"}


def test_text_drops_accented_non_english():
    fr = ("été à côté très élève déjà après être français système économie général pour une société "
          "où les résultats financiers étaient présentés devant le conseil d'administration chaque année").split()
    rng = random.Random(5)
    doc = "\n".join(" ".join(rng.choice(fr) for _ in range(30)) + "." for _ in range(20))
    r = cleaning.clean_document(doc, "text")
    assert not r.kept and r.reason == "non_english"


def test_text_strips_boilerplate_lines():
    body = prose(12) + "\nTable of Contents\nPage 3 of 40\n"
    r = cleaning.clean_document(body, "text")
    assert r.kept and "Table of Contents" not in r.text and "Page 3 of 40" not in r.text


def test_text_redacts_pii_in_kept_output():
    r = cleaning.clean_document(prose(12) + "\nContact jane.doe@mail.com for details about the supply agreement and the contract.\n", "text")
    assert r.kept and "jane.doe@mail.com" not in r.text


def test_light_keeps_short_lines_and_math():
    doc = "Let $x$ be real.\n" + prose(12, seed=3)
    r = cleaning.clean_document(doc, "light")
    assert r.kept and "Let $x$ be real." in r.text


# ---------- python ----------

GOOD_PY = '''import pandas as pd


def load(path: str) -> pd.DataFrame:
    """Load a csv file and drop empty rows."""
    df = pd.read_csv(path)
    return df.dropna(how="all")


def summarize(df: pd.DataFrame) -> pd.Series:
    return df.groupby("region")["revenue"].sum().sort_values(ascending=False)
''' * 2


def test_python_keeps_valid_code_and_preserves_newlines():
    r = cleaning.clean_document(GOOD_PY, "code")
    assert r.kept and "\n    df = pd.read_csv(path)\n" in r.text


def test_python_drops_syntax_errors():
    assert cleaning.clean_document("def broken(:\n    pass\n" * 30, "code").reason == "syntax_error"


def test_python_drops_autogenerated():
    code = "# This file is auto-generated. DO NOT EDIT.\n" + GOOD_PY
    assert cleaning.clean_document(code, "code").reason == "autogenerated"


def test_python_drops_too_short_and_too_long():
    assert cleaning.clean_document("x = 1\n", "code").reason == "too_short"
    huge = "x = 1\n" * 30_000
    assert cleaning.clean_document(huge, "code").reason == "too_long"


def test_python_drops_long_lines():
    code = GOOD_PY + "DATA = '" + "A1" * 700 + "'\n"
    assert cleaning.clean_document(code, "code").reason == "long_lines"


def test_python_drops_comment_heavy_files():
    code = "# comment line number one for padding purposes\n" * 40 + "x = 1\n"
    assert cleaning.clean_document(code, "code").reason == "comment_heavy"


def test_python_drops_files_with_secrets():
    code = GOOD_PY + "API_KEY = 'AKIAIOSFODNN7EXAMPLE'\n"
    assert cleaning.clean_document(code, "code").reason == "secret"


def test_python_redacts_email():
    code = GOOD_PY + "AUTHOR = 'jane.doe@corp.com'\n"
    r = cleaning.clean_document(code, "code")
    assert r.kept and "jane.doe@corp.com" not in r.text


# ---------- sql ----------

GOOD_SQL = """-- monthly revenue by region
SELECT r.name AS region, DATE_TRUNC('month', o.order_date) AS month, SUM(o.amount) AS revenue
FROM orders o
JOIN regions r ON r.id = o.region_id
WHERE o.status = 'shipped'
GROUP BY r.name, DATE_TRUNC('month', o.order_date)
ORDER BY month, revenue DESC;

CREATE TABLE suppliers (id INT PRIMARY KEY, name VARCHAR(100) NOT NULL, lead_time_days INT);
"""


def test_sql_keeps_valid_queries():
    r = cleaning.clean_document(GOOD_SQL, "sql")
    assert r.kept and "SELECT r.name" in r.text


def test_sql_drops_unparseable():
    assert cleaning.clean_document("SELEKT ??? FROM ((( nothing here at all, really. " * 12, "sql").reason == "parse_error"


def test_sql_drops_insert_dumps():
    dump = "INSERT INTO t VALUES (1,'a','b');\n" * 200
    assert cleaning.clean_document(dump, "sql").reason == "data_dump"


def test_sql_keeps_files_with_few_inserts():
    r = cleaning.clean_document(GOOD_SQL + "INSERT INTO suppliers VALUES (1, 'Acme', 7);\n", "sql")
    assert r.kept


# ---------- notebooks ----------

NB = ("# Sales analysis\n\nWe load the data and look at monthly revenue trends across regions.\n\n"
      "```python\nimport pandas as pd\ndf = pd.read_csv('sales.csv')\nprint(df.head())\n```\n\n"
      "The table above shows the first rows. Next we aggregate revenue by month.\n\n"
      "```python\nmonthly = df.groupby('month')['revenue'].sum()\nprint(monthly)\n```\n") * 2


def test_notebook_keeps_markdown_and_code():
    r = cleaning.clean_document(NB, "notebook")
    assert r.kept and "```python" in r.text


def test_notebook_strips_base64_images():
    blob = "data:image/png;base64," + "QUJD" * 500
    r = cleaning.clean_document(NB + f"![img]({blob})\n", "notebook")
    assert r.kept and "base64" not in r.text


def test_notebook_drops_tiny():
    assert cleaning.clean_document("# hi\n", "notebook").reason == "too_short"


# ---------- dispatch / result ----------

def test_unknown_kind_raises():
    with pytest.raises(ValueError):
        cleaning.clean_document("text", "video")


def test_clean_result_reports_sizes():
    r = cleaning.clean_document(GOOD_PY, "code")
    assert r.raw_chars == len(GOOD_PY) and r.clean_chars == len(r.text)


def test_clean_is_deterministic():
    assert cleaning.clean_document(GOOD_SQL, "sql") == cleaning.clean_document(GOOD_SQL, "sql")


def test_sql_parser_internal_errors_do_not_crash(monkeypatch):
    import sqlglot

    def boom(*args, **kwargs):
        raise AttributeError("'NoneType' object has no attribute 'args'")

    monkeypatch.setattr(sqlglot, "parse", boom)
    assert cleaning.clean_document(GOOD_SQL, "sql").reason == "parse_error"


def test_python_keeps_nbconvert_scripts_with_markdown_comments():
    body = "".join(
        f"# In[{i}]:\n\n\n# # Step {i}\n# We explore the data in this cell.\n# More notes about the analysis.\n"
        f"# ## Details {i}\n# Observations are listed below for the reader.\n\n"
        f"values_{i} = [n * {i} for n in range(10)]\nprint(sum(values_{i}))\n\n"
        for i in range(1, 7))
    r = cleaning.clean_document("#!/usr/bin/env python\n# coding: utf-8\n\n" + body, "code")
    assert r.kept, r.reason


def test_sql_ignores_comments_when_checking_parse():
    q = ("# 1. 查询工资最低的员工信息: last_name, salary\n\n#①查询最低的工资\nSELECT MIN(salary)\nFROM employees;\n\n"
         "#②查询last_name,salary\nSELECT last_name, salary\nFROM employees\nWHERE salary = (SELECT MIN(salary) FROM employees);\n"
         "-- 方式一\nSELECT department_id, AVG(salary) AS avg_sal FROM employees GROUP BY department_id;\n")
    r = cleaning.clean_document(q, "sql")
    assert r.kept, r.reason
    assert "查询工资最低" in r.text  # comments are kept in the output
