"""SFT v4 templates: plain selects, top-N by an existing column, simple filters and aggregates.

v3 over-used joins and aggregates (e.g. it answered "top suppliers by rating" with a nonsense subquery).
These cover the simple case where the needed column already exists. Three templates are held out for the
unseen-template test (holdout=True): shortest lead time, lowest loan rate and average warehouse capacity.
"""

from __future__ import annotations

from viki_slm_125m.sft.domain.domain_templates import SqlTemplate, TOP_N, _SC, choice, pick

_FIN = "finance"

V4_SQL_TEMPLATES: tuple[SqlTemplate, ...] = (
    # ---- supply chain
    SqlTemplate(_SC, "sc_top_rated",
                ("Which {n} suppliers have the highest rating?", "Which {n} suppliers have the highest average rating?",
                 "List the top {n} suppliers by rating.", "Show the {n} best rated suppliers."),
                "SELECT name, rating FROM suppliers ORDER BY rating DESC LIMIT {n}", {"n": TOP_N}),
    SqlTemplate(_SC, "sc_suppliers_in_country",
                ("List the suppliers in {c}.", "Which suppliers are based in {c}?", "Show all suppliers from {c} with their rating."),
                "SELECT name, rating FROM suppliers WHERE country = '{c}' ORDER BY rating DESC", {"c": pick("suppliers", "country")}),
    SqlTemplate(_SC, "sc_avg_rating",
                ("What is the average supplier rating?", "What is the mean rating across all suppliers?"),
                "SELECT ROUND(AVG(rating), 2) AS avg_rating FROM suppliers"),
    SqlTemplate(_SC, "sc_avg_rating_country",
                ("What is the average supplier rating in each country?", "Show the mean rating of suppliers by country."),
                "SELECT country, ROUND(AVG(rating), 2) AS avg_rating FROM suppliers GROUP BY country ORDER BY avg_rating DESC"),
    SqlTemplate(_SC, "sc_longest_lead",
                ("Which {n} suppliers have the longest lead time?", "List the {n} suppliers with the slowest lead time in days."),
                "SELECT name, lead_time_days FROM suppliers ORDER BY lead_time_days DESC LIMIT {n}", {"n": TOP_N}),
    SqlTemplate(_SC, "sc_priciest_products",
                ("Which {n} products have the highest unit cost?", "List the {n} most expensive products.",
                 "Show the top {n} products by unit cost."),
                "SELECT name, unit_cost FROM products ORDER BY unit_cost DESC LIMIT {n}", {"n": TOP_N}),
    SqlTemplate(_SC, "sc_products_in_category",
                ("List the products in the {c} category.", "Which products belong to {c}?", "Show the name and unit cost of every {c} product."),
                "SELECT name, unit_cost FROM products WHERE category = '{c}' ORDER BY unit_cost DESC", {"c": pick("products", "category")}),
    SqlTemplate(_SC, "sc_biggest_warehouses",
                ("Which warehouses have the largest capacity?", "List warehouses by capacity, largest first.", "Show each warehouse city and its capacity."),
                "SELECT city, capacity FROM warehouses ORDER BY capacity DESC"),
    SqlTemplate(_SC, "sc_costliest_shipments",
                ("Which {n} shipments had the highest freight cost?", "Show the {n} most expensive shipments."),
                "SELECT shipment_id, carrier, freight_cost FROM shipments ORDER BY freight_cost DESC LIMIT {n}", {"n": TOP_N}),
    SqlTemplate(_SC, "sc_open_orders",
                ("List the open purchase orders.", "Which purchase orders are still open? Show the oldest {n}.", "Show {n} open purchase orders by order date."),
                "SELECT po_id, supplier_id, order_date, quantity FROM purchase_orders WHERE status = 'open' ORDER BY order_date LIMIT {n}",
                {"n": TOP_N}),
    SqlTemplate(_SC, "sc_big_orders_count",
                ("How many purchase orders have a quantity above {q}?", "Count the orders with more than {q} units."),
                "SELECT COUNT(*) AS big_orders FROM purchase_orders WHERE quantity > {q}", {"q": choice(100, 250, 500)}),
    SqlTemplate(_SC, "sc_low_stock_rows",
                ("Which inventory records have fewer than {t} units on hand?", "List stock levels under {t} units."),
                "SELECT product_id, warehouse_id, quantity_on_hand FROM inventory WHERE quantity_on_hand < {t} ORDER BY quantity_on_hand LIMIT 20",
                {"t": choice(20, 50, 100)}),
    SqlTemplate(_SC, "sc_total_capacity",
                ("What is the total warehouse capacity?", "How much capacity do all warehouses have in total?"),
                "SELECT SUM(capacity) AS total_capacity FROM warehouses"),
    SqlTemplate(_SC, "sc_supplier_count_country",
                ("How many suppliers are there in each country?", "Count suppliers per country."),
                "SELECT country, COUNT(*) AS suppliers FROM suppliers GROUP BY country ORDER BY suppliers DESC"),
    # ---- finance
    SqlTemplate(_FIN, "fin_top_balances",
                ("Which {n} accounts have the highest balance?", "List the top {n} accounts by balance."),
                "SELECT account_id, account_type, balance FROM accounts ORDER BY balance DESC LIMIT {n}", {"n": TOP_N}),
    SqlTemplate(_FIN, "fin_customers_in_country",
                ("List the customers in {c}.", "Which customers are from {c}?", "Show the name and segment of every customer in {c}."),
                "SELECT name, segment FROM customers WHERE country = '{c}' ORDER BY name", {"c": pick("customers", "country")}),
    SqlTemplate(_FIN, "fin_avg_rate",
                ("What is the average loan interest rate?", "What is the mean interest rate across all loans?"),
                "SELECT ROUND(AVG(interest_rate), 2) AS avg_interest_rate FROM loans"),
    SqlTemplate(_FIN, "fin_avg_rate_status",
                ("What is the average interest rate for each loan status?", "Show the mean loan rate by status."),
                "SELECT status, ROUND(AVG(interest_rate), 2) AS avg_interest_rate FROM loans GROUP BY status ORDER BY avg_interest_rate DESC"),
    SqlTemplate(_FIN, "fin_largest_loans",
                ("Which {n} loans have the largest principal?", "List the {n} biggest loans."),
                "SELECT loan_id, principal, status FROM loans ORDER BY principal DESC LIMIT {n}", {"n": TOP_N}),
    SqlTemplate(_FIN, "fin_risk_customers",
                ("How many customers have a {r} risk rating?", "Count the {r} risk customers."),
                "SELECT COUNT(*) AS customers FROM customers WHERE risk_rating = '{r}'", {"r": pick("customers", "risk_rating")}),
    SqlTemplate(_FIN, "fin_txn_count_channel",
                ("How many transactions went through each channel?", "Count transactions per channel."),
                "SELECT channel, COUNT(*) AS transactions FROM transactions GROUP BY channel ORDER BY transactions DESC"),
    SqlTemplate(_FIN, "fin_max_balance_type",
                ("What is the highest balance for each account type?", "Show the largest account balance per type."),
                "SELECT account_type, MAX(balance) AS max_balance FROM accounts GROUP BY account_type ORDER BY max_balance DESC"),
    SqlTemplate(_FIN, "fin_biggest_txns",
                ("Which {n} transactions have the largest amount?", "Show the {n} biggest transactions."),
                "SELECT txn_id, txn_date, amount, channel FROM transactions ORDER BY amount DESC LIMIT {n}", {"n": TOP_N}),
    SqlTemplate(_FIN, "fin_loans_by_status",
                ("How many loans have the status {s}?", "Count the loans that are {s}."),
                "SELECT COUNT(*) AS loans FROM loans WHERE status = '{s}'", {"s": pick("loans", "status")}),
    SqlTemplate(_FIN, "fin_total_balance",
                ("What is the total balance across all accounts?", "How much money is held in all accounts combined?"),
                "SELECT ROUND(SUM(balance), 2) AS total_balance FROM accounts"),
    # ---- held out for the unseen-template test
    SqlTemplate(_SC, "sc_shortest_lead",
                ("Which {n} suppliers have the shortest lead time?", "List the {n} fastest suppliers by lead time in days."),
                "SELECT name, lead_time_days FROM suppliers ORDER BY lead_time_days ASC LIMIT {n}", {"n": TOP_N}, holdout=True),
    SqlTemplate(_FIN, "fin_lowest_rate_loans",
                ("Which {n} loans have the lowest interest rate?", "List the {n} cheapest loans by interest rate."),
                "SELECT loan_id, interest_rate, status FROM loans ORDER BY interest_rate ASC LIMIT {n}", {"n": TOP_N}, holdout=True),
    SqlTemplate(_SC, "sc_avg_capacity",
                ("What is the average warehouse capacity?", "What is the mean capacity of our warehouses?"),
                "SELECT ROUND(AVG(capacity), 1) AS avg_capacity FROM warehouses", holdout=True),
)
